version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - "dependencies"
    groups:
      npm:
        patterns: 
          - "*"
  - directory: /
    package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    groups:
      github-actions:
        patterns: 
          - "*"
