name: Release Management

on:
  push:
    branches:
      - main

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Build Changelog"
        id: github_release
        uses: mikepenz/release-changelog-builder-action@main
        with:
          configuration: ".github/configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
