name: Verify labels for release

on:
  pull_request_target:
   types: [opened, labeled, unlabeled, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: jesusvasquez333/verify-pr-label-action@657d111bbbe13e22bbd55870f1813c699bde1401 #v1.4.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'bug, enhancement, maintenance'
          pull-request-number: '${{ github.event.pull_request.number }}'
